apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  slack-token: xoxb-5199775546-1435924739494-yAycwvijPkliodIx7CWW8RR7
  email-username: $EMAIL_USER
  email-password: $PASSWORD
